# k8s/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verus-backend
  template:
    metadata:
      labels:
        app: verus-backend
    spec:
      containers:
      - name: verus-backend
        image: ia984818/verus-backend:v4
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/"
        - name: DB_NAME
          value: "verus_db"
        - name: JWT_SECRET_KEY
          value: "A-very-long-and-secure-default-secret-key-1234567890ABCDEF"
        - name: DEBUG
          value: "true"
        - name: PORT
          value: "5000"
---
# k8s/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: verus-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
