apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verus-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service # Matches name in frontend-service.yaml
            port:
              number: 80
      - path: /text-process
        pathType: Prefix
        backend:
          service:
            name: backend-text-process-service
            port:
              number: 5000
      - path: /image-process
        pathType: Prefix
        backend:
          service:
            name: backend-image-process-service
            port:
              number: 5000
      - path: /video-process
        pathType: Prefix
        backend:
          service:
            name: backend-video-process-service
            port:
              number: 5000
      - path: /audio-process
        pathType: Prefix
        backend:
          service:
            name: backend-audio-process-service
            port:
              number: 5000
      - path: /image-predict
        pathType: Prefix
        backend:
          service:
            name: backend-image-predict-service
            port:
              number: 5000
      - path: /text-predict
        pathType: Prefix
        backend:
          service:
            name: backend-text-predict-service
            port:
              number: 5000
      - path: /video-predict
        pathType: Prefix
        backend:
          service:
            name: backend-video-predict-service
            port:
              number: 5000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 5000
